Frameio/rolodex

- lib/rolodex.ex
- lib/rolodex/config.ex
- lib/rolodex/route.ex
- test/rolodex/route_test.exs
- test/rolodex_test.exs
- test/support/mocks.ex
Allows users to filter out routes from the documentation output. Filters are defined in the Rolodex config and can be either a map of match metadata or a match function. Match checks are done in `Rolodex.Route.matches_filter?/2`.
> feat(RouteFiltering): Updates to support route filtering

- lib/mix/tasks/rolodex.ex
- lib/mix/tasks/rolodex.gen.docs.ex
- lib/rolodex.ex
- lib/rolodex/config.ex
- lib/rolodex/route.ex
- lib/rolodex/writers/file_writer.ex
- mix.exs
- test/rolodex/config_test.exs
- test/rolodex/route_test.exs
- test/support/mocks.ex
Various pieces of cleanup ahead of MVP and to ensure things work as expected for our own API docs use cases.
- Handle missing controller action methods
- Restructure the mix tasks
- Nested config parsing for writer and pipelines
> MVP Cleanup

- lib/rolodex/config.ex
- lib/rolodex/processors/swagger.ex
- test/rolodex/processors/swagger_test.exs
- test/rolodex_test.exs
See: https://swagger.io/docs/specification/api-host-and-base-path/
> feat(ServerURLs): Specify shared base URLs for API paths

- lib/rolodex/config.ex
- lib/rolodex/processors/swagger.ex
- lib/rolodex/route.ex
- lib/rolodex/schema.ex
- test/rolodex/processors/swagger_test.exs
- test/rolodex/schema_test.exs
- test/rolodex_test.exs
- test/support/mocks.ex
For [PLATFORM-396](https://frame-io.atlassian.net/browse/PLATFORM-396)
1. Add support for an `enum` opt on fields. Should be a list of valid values for the field. In the Swagger processor, we look for this now.
2. Ensure we serialize field descriptions into Swagger JSON.
3. Better support for required fields in Swagger JSON output. For objects, we need to collected all required props into a top-level array.
4. Fix: support shared responses for pipelines via config
> Field and config metadata updates

- lib/rolodex.ex
- lib/rolodex/config.ex
- lib/rolodex/content_utils.ex
- lib/rolodex/field.ex
- lib/rolodex/processors/processor.ex
- lib/rolodex/processors/swagger.ex
- lib/rolodex/request_body.ex
- lib/rolodex/response.ex
- lib/rolodex/route.ex
- test/rolodex/field_test.exs
- test/rolodex/processors/swagger_test.exs
- test/rolodex/request_body_test.exs
- test/rolodex/route_test.exs
- test/rolodex_test.exs
- test/support/mocks/controllers.ex
- test/support/mocks/request_bodies.ex
- test/support/mocks/routers.ex
For [PLATFORM-425](https://frame-io.atlassian.net/browse/PLATFORM-425)
These look very similar to reusable response schemas defined via `Rolodex.Response`. So much so that a chunk of this diff is abstracted macro logic shared b/t Response and RequestBody into an (undocumented) helper module `Rolodex.ContentUtils`.
Key updates here:
- Define reusable request body schemas via `Rolodex.RequestBody` macros
- Updates to the processing pipeline to handle these new refs
- Refactor to ensure users can still pass in bare maps/keywords to define one-off request body or response schemas. In those cases, we'll use a default content-type value set in Config when serializing to OpenAPI
> Rolodex.RequestBody: Define shared request bodies

- lib/rolodex/config.ex
- lib/rolodex/processors/swagger.ex
- lib/rolodex/route.ex
- lib/rolodex/utils.ex
- test/rolodex/route_test.exs
- test/rolodex_test.exs
- test/support/mocks/controllers.ex
- test/support/mocks/routers.ex
A Phoenix controller action can be used multiple times for different
router paths. The docs for each path may differ significantly, so we
want a way to support multiple doc definitions per action function.
Our approach: a top level `multi: true` flag on the @doc annotation.
Every other top-level key corresponds to a router path. The value for
each path key is the docs for that router path.
> [PLATFORM-431] Support documenting multiple use action functions

- lib/rolodex/processors/swagger.ex
- test/rolodex/processors/swagger_test.exs
- test/rolodex_test.exs
- OpenAPI 3.0 requires that we _omit_ the `requestBody` field for a
route doc when there is no request body required
- Properly key response examples
> [PLATFORM-543] Some dogfooding fixes

- lib/rolodex.ex
- lib/rolodex/processors/swagger.ex
- mix.exs
Reworks https://github.com/Frameio/rolodex/pull/31
Closes https://github.com/Frameio/rolodex/issues/27
At the moment, even with a large Phoenix router, we don't need Flow
to reduce load when generating docs. In fact, the overhead introduced
by Flow (spinning up GenStage processes) means that without Flow docs
generate faster.
> Removes Flow

- lib/rolodex/schema.ex
- test/rolodex/processors/swagger_test.exs
- test/rolodex/schema_test.exs
- test/rolodex_test.exs
- test/support/mocks/schemas.ex
Rather than define a bunch of `__field__/1` functions on the caller
module as the `field/3` macro is invoked, we only collect field
definition metadata in an accumulator attribute. Later, we serialize
the field definitions together into a formatted map on demand via
`__schema__(:fields)`.
This change will allow users to define fields on their schemas in
for comprehensions or maps, without any compiler warnings about
unmatchable function heads.
> [PLATFORM-543] Refactor Rolodex.Schema.field/3 macro

- lib/rolodex/processors/swagger.ex
- test/rolodex/processors/swagger_test.exs
- test/rolodex_test.exs
> [PLATFORM-543] Serialize route tags into OpenAPI 3.0 JSON

- lib/rolodex/processors/swagger.ex
- lib/rolodex/route.ex
- test/rolodex/processors/swagger_test.exs
- test/rolodex_test.exs
Adds support for Swagger [`operationId`](https://swagger.io/docs/specification/paths-and-operations/)
> [PLATFORM-398] add support for operationId

- lib/rolodex.ex
- lib/rolodex/content_utils.ex
- lib/rolodex/field.ex
- lib/rolodex/headers.ex
- lib/rolodex/processors/swagger.ex
- lib/rolodex/request_body.ex
- lib/rolodex/response.ex
- lib/rolodex/route.ex
- lib/rolodex/schema.ex
- test/rolodex/headers_test.exs
- test/rolodex/processors/swagger_test.exs
- test/rolodex/request_body_test.exs
- test/rolodex/response_test.exs
- test/rolodex/route_test.exs
- test/rolodex_test.exs
- test/support/mocks/controllers.ex
- test/support/mocks/headers.ex
- test/support/mocks/responses.ex
We forgot to add support for defining response headers! That's the primary
addition this PR makes. In the process, we've also added support for defining
reusable headers via macros exported in the `Rolodex.Headers` module. The DSL
is very similar to what we've put together so far for schemas/responses/bodies.
Some highlights:
- You can now define shared headers via `Rolodex.Headers`
- Shared headers can be used in either responses OR route doc annotations (i.e.
request headers)
- For OpenAPI 3, we never serialize headers as shared component refs b/c that
isn't supported
- Removed documented support for nested schemas in parameters (path, query, header),
since this isn't actually supported by OpenAPI 3. We weren't really testing against
it anyway.
> Add support for response headers, reusable headers

- lib/rolodex/content_utils.ex
- lib/rolodex/processors/swagger.ex
- lib/rolodex/request_body.ex
- lib/rolodex/response.ex
- test/rolodex/request_body_test.exs
- test/rolodex/response_test.exs
- test/rolodex_test.exs
- test/support/mocks/controllers.ex
- test/support/mocks/responses.ex
Sometimes, you'll want to make multiple calls to the `headers/1` macro
when defining a response. This is often to use two or more shared
response headers modules for a specific response.
Via diff, we add support for multiple calls. All the headers passed
in to the response will ultimately be merged together when serialized.
> [PLATFORM-580] Support multiple response headers calls

- lib/mix/tasks/rolodex.gen.docs.ex
- lib/rolodex.ex
- lib/rolodex/config.ex
- lib/rolodex/route.ex
- lib/rolodex/writers/file_writer.ex
- lib/rolodex/writers/writer.ex
- test/rolodex/config_test.exs
- test/rolodex/route_test.exs
- test/rolodex_test.exs
Rolodex can now serialize and write docs to multiple targets for a
single Phoenix router. This is helpful for cases where you want
more than one documentation source for a single API (e.g. public and
private API docs).
To accomplish this goal, we're introducing the concept of "render groups".
A render group is a combination of: (optional) filters, a processor, a
writer, and writer options. Together, they encapsulate Rolodex's render
logic: serialization and writing. You can specify as many render groups as
you'd like in your Rolodex config module to generate as many documentation
forms of your API!
> Add render groups support

- lib/rolodex.ex
- lib/rolodex/config.ex
- lib/rolodex/processors/open_api.ex
- test/rolodex/processors/open_api_test.exs
The JSON result this processor outputs is compliant to the OpenAPI 3.0
spec, which is not restrictive to the Swagger platform. I think the
naming of the processor should reflect this fact.
> Rename Swagger processor to OpenAPI

- lib/mix/tasks/rolodex.gen.docs.ex
- lib/rolodex/config.ex
- lib/rolodex/content_utils.ex
- lib/rolodex/field.ex
- lib/rolodex/processors/open_api.ex
- lib/rolodex/schema.ex
- test/rolodex/processors/open_api_test.exs
- test/rolodex/schema_test.exs
- test/rolodex_test.exs
- test/support/mocks/schemas.ex
1. Add support for more OpenAPI string formats. When we encounter a
schema or paremeter field like `type: <format>` where the format
is a valid OpenAPI string format, the docs output will become
`type: "string", format: <format>".
2. Support list field shorthand for schema fields (we already do this
for schemas used in responses and request bodies).
> Field formatting updates

- lib/rolodex/schema.ex
- test/rolodex/processors/open_api_test.exs
- test/rolodex/schema_test.exs
- test/rolodex_test.exs
- test/support/mocks/schemas.ex
New addition to the schema DSL. With partials, you can merge
parameters from another schema into a new schema definition. This
is especially useful for parameters shared across multiple schemas,
such as pagination metadata.
> [PLATFORM-614] Schema partials

- lib/rolodex/dsl.ex
- lib/rolodex/headers.ex
- lib/rolodex/request_body.ex
- lib/rolodex/response.ex
- lib/rolodex/schema.ex
- test/rolodex/request_body_test.exs
- test/rolodex/response_test.exs
- test/rolodex/schema_test.exs
- test/support/mocks/request_bodies.ex
- test/support/mocks/responses.ex
~NOTE: Blocked by #61~
This refactor adds support for defining request body and response
schemas via an inline macro syntax. This will allow users to leverage
partial schemas in their content bodies, without needing to define
standalone schemas via Rolodex.Schema.
> [PLATFORM-615] Inline schema macros for requests and responses

- lib/rolodex.ex
- lib/rolodex/route.ex
- test/rolodex/route_test.exs
- test/rolodex_test.exs
- test/support/mocks/controllers.ex
- test/support/mocks/routers.ex
- test/support/mocks/schemas.ex
This refactors our support to using schemas in the `query_params`
and `path_params` doc annotation items. Like with headers, we will
serialize these schemas in full in the Route parser. No changes are
needed to the way we serialize params in the OpenAPI processor, b/c
the data passed in will always be a map. I've chosen this approach,
rather than supporting serializing path and query params via component
references because of the slightly different shape of parameter descriptions.
> [PLATFORM-616] Schemas for query and path params

- lib/rolodex/route.ex
- lib/rolodex/utils.ex
- test/rolodex/route_test.exs
- test/rolodex/utils_test.exs
- test/support/mocks/controllers.ex
We currently support documenting controller actions that are used
multiple times across distinct API paths. We also want to support
the case where a controller action is used multiple times across
the same path but different HTTP methods.
> Split multi route actions based on HTTP method

- .gitignore
- lib/rolodex.ex
- lib/rolodex/config.ex
- lib/rolodex/dsl.ex
- lib/rolodex/route.ex
- lib/rolodex/router.ex
- lib/rolodex/router/route_info.ex
- lib/rolodex/utils.ex
- mix.exs
- test/rolodex/config_test.exs
- test/rolodex/route_test.exs
- test/rolodex/router_test.exs
- test/rolodex_test.exs
- test/support/mocks/controllers.ex
- test/support/mocks/phoenix_routers.ex
- test/support/mocks/routers.ex
We were being too clever, and it's caught up to us.
Currently, Rolodex relies heavily on Phoenix when collecting documentation.
Specifically, we use the `__routes__/0` function added to any Phoenix
Router module to access your project's router tree. We then traverse this
tree, collecting doc annotations for each path.
This tight coupling is problematic for a few reasons:
- `__routes__/0` is a private function, and Phoenix router tree a private
data structure. And, it's been removed in Phoenix v1.4.7, effecitvely
breaking Rolodex.
- By default, we document every API path in your router. If you want to
only document a subset, you need to define filter(s) to match against
the routes you want to document only.
Enter `Rolodex.Router`. Going forward, as part of your Rolodex configuration, …
> [PLATFORM-641] Add Rolodex.Router

- .gitignore
- README.md
- lib/rolodex.ex
- lib/rolodex/config.ex
- lib/rolodex/dsl.ex
- lib/rolodex/route.ex
- lib/rolodex/router.ex
- lib/rolodex/router/route_info.ex
- lib/rolodex/utils.ex
- mix.exs
- test/rolodex/config_test.exs
- test/rolodex/route_test.exs
- test/rolodex/router_test.exs
- test/rolodex/utils_test.exs
- test/rolodex_test.exs
- test/support/mocks/controllers.ex
- test/support/mocks/phoenix_routers.ex
- test/support/mocks/routers.ex
- Adds `Rolodex.Router`, a new DSL for defining which routes Rolodex should compile for documentation. This is a breaking change and replaces the filter concept from <= v0.8.1. With this change, Rolodex should work for Phoenix v1.4.7 and greater.
> Release v0.9.0

- lib/rolodex/processors/open_api.ex
- test/rolodex_test.exs
Some OpenAPI 3 documentation renderers error out when processing empty
examples in Request and Response content bodies. So when generating
OpenAPI 3 docs, we will strip out examples when they're empty.
> Strip empty content body examples
